

version: "3.8"

services:

  #  # Notification Service
  notification_service_server:
    container_name: notification_service_server
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
    volumes:
      - ./notifications:/usr/src/app




# Define a shared network for communication
networks:
  digital_wallet_network:
    driver: bridge

